# Generated by Django 5.1.6 on 2025-02-27 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_testentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='is_all_day',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='updated_at',
        ),
    ]
