# Generated by Django 5.1.6 on 2025-02-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_remove_calendarevent_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
