# Generated by Django 5.1.6 on 2025-04-15 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0012_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywellness',
            name='breaks_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='dailywellness',
            name='meals_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='dailywellness',
            name='water_goal',
            field=models.IntegerField(default=8),
        ),
    ]
