# Generated by Django 5.1.6 on 2025-04-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0013_dailywellness_breaks_goal_dailywellness_meals_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywellness',
            name='goal_completed',
            field=models.BooleanField(default=False),
        ),
    ]
