# Generated by Django 5.1.6 on 2025-04-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0014_dailywellness_goal_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywellness',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='dailywellness',
            name='xp',
            field=models.IntegerField(default=0),
        ),
    ]
