# Generated by Django 5.1.6 on 2025-04-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0016_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='custom_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
