# Generated by Django 5.1.6 on 2025-04-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0017_reminder_custom_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendarevent'),
        ),
    ]
